Repository openshift-knative/knative-eventing-operator, pull requests merged in 2019-10, with the labels that each got.

#61 Adding empty spec
  deploy/crds/eventing_v1alpha1_knativeeventing_cr.yaml
Labels: size/XS

#62 patch gcr based image release w/ NetworkPolicy for Openshift
  deploy/resources/knative-eventing-v0.8.0.yaml
Labels: lgtm, size/S

#64 Add Owners file for bot
  OWNERS
Labels: size/S

#63 Eventing 090 operator start
  deploy/olm-catalog/knative-eventing-operator/0.9.0/eventing_v1alpha1_knativeeventing_crd.yaml
  deploy/olm-catalog/knative-eventing-operator/0.9.0/knative-eventing-operator.v0.9.0.clusterserviceversion.yaml
  deploy/olm-catalog/knative-eventing-operator/knative-eventing-operator.package.yaml
  deploy/operator.yaml
  deploy/resources/knative-eventing-v0.9.0.yaml
  version/version.go
Labels: approved, lgtm, size/XXL

#65 remove target ns and add filename
  deploy/olm-catalog/knative-eventing-operator/0.9.0/knative-eventing-operator.v0.9.0.clusterserviceversion.yaml
Labels: approved

#66 updating README to be compliant w/ OCP 4.2+
  README.md
Labels: approved, lgtm, size/S
