Repository openshift-knative/knative-eventing-operator, pull requests merged in 2020-01, with the labels that each got.

#87 Adding Ali to this group
  OWNERS
Labels: approved, do-not-merge/invalid-owners-file, size/XS

#86 Quay.io overring and yaml polishing
  deploy/olm-catalog/knative-eventing-operator/0.11.0/knative-eventing-operator.v0.11.0.clusterserviceversion.yaml
Labels: approved, size/XS

#88 Add SideEffects: None to mutatingWH transformation
  pkg/controller/knativeeventing/knativeeventing_controller.go
Labels: approved, size/S

#89 Get rid of SCC rules added to cluster roles.
  pkg/controller/knativeeventing/knativeeventing_controller.go
Labels: approved, size/M

#90 Removing the NetworkPolicy
  deploy/resources/networkpolicies.yaml
Labels: approved, size/S

#91 Add sideEffects none to the yaml
  deploy/resources/knative-eventing-v0.11.0.yaml
Labels: approved, lgtm, size/XS

#92 Reverting fix for the sideEffects, since we now ship it on the yamls
  pkg/controller/knativeeventing/knativeeventing_controller.go
Labels: approved, lgtm, size/S

#93 Prep for 0.12
  deploy/olm-catalog/knative-eventing-operator/0.12.0/eventing_v1alpha1_knativeeventing_crd.yaml
  deploy/olm-catalog/knative-eventing-operator/0.12.0/knative-eventing-operator.v0.12.0.clusterserviceversion.yaml
  deploy/olm-catalog/knative-eventing-operator/knative-eventing-operator.package.yaml
  deploy/operator.yaml
  deploy/resources/knative-eventing-v0.12.0.yaml
  version/version.go
Labels: approved, lgtm, size/XXL

#94 Updating operator to use quay.io built images for 0.12
  deploy/olm-catalog/knative-eventing-operator/0.12.0/knative-eventing-operator.v0.12.0.clusterserviceversion.yaml
Labels: approved, lgtm, size/XS
