Repository openshift-knative/knative-eventing-operator, pull requests merged in 2020-03, with the labels that each got.

#98 Removing myself from approvers/reviewers
  OWNERS
Labels: approved, size/XS

#100 updating to RHEL 8 / UBI.81.
  build/Dockerfile
Labels: approved, lgtm, size/XS

#99 hide the KnativeEventings APIs
  deploy/olm-catalog/knative-eventing-operator/0.12.0/knative-eventing-operator.v0.12.0.clusterserviceversion.yaml
Labels: approved, lgtm, size/XS

#101 one FROM...
  build/Dockerfile
Labels: approved

#102 removing NetworkPolicy override uRL
  deploy/olm-catalog/knative-eventing-operator/0.12.0/knative-eventing-operator.v0.12.0.clusterserviceversion.yaml
Labels: approved, lgtm

#103 DevPreview Eventing 0.13
  deploy/olm-catalog/knative-eventing-operator/0.13.0/eventing_v1alpha1_knativeeventing_crd.yaml
  deploy/olm-catalog/knative-eventing-operator/0.13.0/knative-eventing-operator.v0.13.0.clusterserviceversion.yaml
  deploy/olm-catalog/knative-eventing-operator/knative-eventing-operator.package.yaml
  deploy/operator.yaml
  deploy/resources/knative-eventing-v0.12.0.yaml
  deploy/resources/knative-eventing-v0.13.0.yaml
  version/version.go
Labels: approved, lgtm
